version: '3'

vars:
  # 問題に応じて設定する必要がある変数
  USER: isucon
  BIN_NAME: 
  BUILD_DIR: 
  SERVICE_NAME:
  ENV_FILE:

  # 基本共通の変数 -------
  DB_PATH: /etc/mysql
  NGINX_PATH: /etc/nginx
  SYSTEMD_PATH: /etc/systemd/system

  NGINX_LOG: /var/log/nginx/access.log
  DB_SLOW_LOG: /var/log/mysql/mysql-slow.log

  # http://localhost:19999/netdata.confのdirectories.webで確認可能
  NETDATA_WEBROOT_PATH: /var/lib/netdata/www
  NETDATA_CUSTOM_HTML: ~/tool-config/netdata/*

env:
  SERVER_ID: s1

tasks:
  # bench:
  # pprof:
  # fgprof:
  # send-data:

  setup:
    desc: インスタンスを立てたら最初に実行する
    cmds:
      - task: install-tools
      - task: git-setup

  get-conf:
    desc: 設定ファイルを取得してgit管理下に配置する
    cmds:
      - task: check-server-id
      - task: get-db-conf
      - task: get-nginx-conf
      - task: get-service-file
      - task: get-env-file

  # 本番中直接実行しないもの ---------
  install-tools:
    vars: 
      ALP_VERSION: v1.0.21
      DOOL_VERSION: "1.3.0"
    cmds:
      - sudo apt update
      - sudo apt upgrade
      - sudo apt install -y percona-toolkit git unzip snapd graphviz tree wget
      # doolのインストール
      - wget -O dtool.zip https://github.com/scottchiefbaker/dool/archive/refs/tags/v{{.DOOL_VERSION}}.zip
      - unzip dool.zip
      - cd dool/dool-{{.DOOL_VERSION}} && python install.py
      - rm dool.zip dool
      # alpのインストール
      - wget https://github.com/tkuchiki/alp/releases/download/{{.ALP_VERSION}}/alp_linux_amd64.zip
      - unzip alp_linux_amd64.zip
      - sudo install alp /usr/local/bin/alp
      - rm alp_linux_amd64.zip alp
      # netdataのインストール
      - wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh --no-updates --stable-channel --disable-telemetry
  
  git-setup:
    cmds:
      - git config --global user.email "isucon@example.com"
      - git config --global user.name "isucon"
      # deploykeyの作成
      - ssh-keygen -t ed25519
  
  # 環境変数SERVER_IDが登録されているかを検証する
  # SERVER_IDの値を使うコマンドでは、基本preconditionsで呼ぶようにする
  check-server-id:
    preconditions:
      - sh: '[ $SERVER_ID != "" ]'
        msg: Env SERVER_ID is unset
    cmd: echo "SERVER_ID = $SERVER_ID"
  
  get-db-conf:
    preconditions:
      - task: check-server-id
    cmds:
      - sudo cp -R {{.DB_PATH}}/* ~/$SERVER_ID/etc/mysql
      - sudo chown {{.USER}} -R ~/$SERVER_ID/etc/mysql
  
  get-nginx-conf:
    preconditions:
      - task: check-server-id
    cmds:
      - sudo cp -R {{.NGINX_PATH}}/* ~/$SERVER_ID/etc/nginx
      - sudo chown {{.USER}} -R ~/$SERVER_ID/etc/nginx
  
  get-service-file:
    preconditions:
      - task: check-server-id
    cmds:
      - sudo cp {{.SYSTEMD_PATH}}/{{.SERVICE_NAME}} ~/$SERVER_ID/etc/systemd/system/{{.SERVICE_NAME}}
      - sudo chown {{.USER}} ~/$SERVER_ID/etc/systemd/system/{{.SERVICE_NAME}}
  
  get-env-file:
    preconditions:
      - task: check-server-id
    cmds:
      - cp ~/{{.ENV_FILE}} ~/$SERVER_ID/home/isucon/{{.ENV_FILE}}
  
  # 設定ファイルの配置
  deploy-conf:
    cmds:
      - task: check-server-id
      - task: deploy-db-conf
      - task: deploy-nginx-conf
      - task: deploy-service-file
      - task: deploy-envfile

  deploy-db-conf:
    preconditions:
      - task: check-server-id
    cmds:
      - sudo cp -R ~/$SERVER_ID/etc/mysql/* {{.DB_PATH}}
  
  deploy-nginx-conf:
    preconditions:
      - task: check-server-id
    cmds:
      - sudo cp -R ~/$SERVER_ID/etc/nginx/* {{.NGINX_PATH}}

  deploy-service-file:
    preconditions:
      - task: check-server-id
    cmds:
      - sudo cp ~/$SERVER_ID/etc/systemd/system/{{.SERVICE_NAME}} {{.SYSTEMD_PATH}}/{{.SERVICE_NAME}}

  deploy-envfile:
    preconditions:
      - task: check-server-id

  test:
    cmds:
      - task check-server-id >> test.txt
